version: '3'
services:
  client:
    image: atorre98/tms_client:latest
    build: 
      context: ./client
      dockerfile: Dockerfile
    networks:
      - tms_net
    ports:
      - 5173:5173
    depends_on: 
      - server

  server:
    image: atorre98/tms_server:latest
    build: 
      context: ./server
      dockerfile: Dockerfile
    networks:
      - tms_net
    ports:
      - 3001:3001

networks:
  tms_net:
    driver: bridge