name: Build and push images

on: 
  push:
    branches: build-action-attempt
  #pull_request:
   #   branches:
    #    - dev
     #   - build-action-attempt
      #types:
       # - closed
jobs:
    build_and_push:
        name: Build and push Docker images to Docker Hub
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Login to Docker Hub 
              uses: docker/login-action@v2
              with:
                username: ${{  secrets.DOCKERHUB_USERNAME  }}
                password: ${{  secrets.DOCKERHUB_TOKEN  }}
            

            - name: Create Docker build context (multi-arch)
              run: |
                cd code/
                docker buildx create --use

            - name: Build client image
              run: |
                cd code/client/
                docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKERHUB_USERNAME }}/tms_client:latest --push .
            
            - name: Build server image
              run: |
                cd code/server/
                docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKERHUB_USERNAME }}/tms_server:latest --push .


