name: Build and push images

on: 
  push:
    branches: build-action-attempt
  #pull_request:
   #   branches:
    #    - dev
     #   - build-action-attempt
      #types:
       # - closed
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Setup QEMU
            uses: docker/setup-qemu-action@v3

          - name: Setup Buildx
            uses: docker/setup-buildx-action@v3

          - name: Login to Docker Hub 
            uses: docker/login-action@v3
            with:
              username: ${{  secrets.DOCKERHUB_USERNAME  }}
              password: ${{  secrets.DOCKERHUB_TOKEN  }}
          
          - name: Build and push client
            uses: docker/build-push-action@v5
            with:
              context: code/client/
              platforms: linux/amd64, linux/arm64
              push: true
              tags: ${{  secrets.DOCKERHUB_USERNAME  }}/tms_client:latest
        
          - name: Build and push server
            uses: docker/build-push-action@v5
            with:
              context: code/server/
              platforms: linux/amd64, linux/arm64
              push: true
              tags: ${{  secrets.DOCKERHUB_USERNAME  }}/tms_server:latest
